<?php
$_brandCollection = $block->getCollection();
$show_brand_name = $this->getConfig('brand_list_page/show_brand_name');
?>
<?php if ( $total = $_brandCollection->count() ): ?>
<div class="brandlist">
	<div class="block-content">
		<?php foreach ($_brandCollection as $_brand): ?>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="brand-item">
				<div class="brand-image"><a href="<?= $_brand->getUrl(); ?>" title="<?= $_brand->getName(); ?>"><img src="<?= $_brand->getThumbnailUrl(); ?>" alt="<?= $_brand->getName(); ?>"/></a></div>
				<?php if($show_brand_name): ?>
				<div class="brand-name"><a href="<?= $_brand->getUrl(); ?>" title="<?= $_brand->getName(); ?>"><?= $_brand->getName() ?></a></div>
				<?php endif; ?>
			</div>
		</div>
		<?php endforeach ?>
	</div>
	<?php if($html = $block->getChildHtml('toolbar')): ?>
	<div class="brand-toolbar  toolbar toolbar-products">
		<?= $html; ?>
	</div>
	<?php endif; ?>
</div>
<?php else: ?>
<div class="message info empty"><div><?= __('We can\'t find brand matching the selection.'); ?></div></div>
<?php endif; ?>