<?php
$brandCollection = $this->getBrandCollection();
$data = $this->helper('Ves\Brand\Helper\Data');
$brand_layout_listing = $data->getConfig("product_view_page/brand_layout_listing");
$show_brand_text = $data->getConfig("product_view_page/show_brand_text");
$show_brand_description = $data->getConfig("product_view_page/show_brand_description");
$brand_text = $data->getConfig("product_view_page/brand_text");
$brand_text = $brand_text?$brand_text:__('Brands: ');
$show_brand_image = $data->getConfig("product_view_page/show_brand_image");
$show_brand_name = $data->getConfig("product_view_page/show_brand_name");
?>
<?php if($brandCollection && $brandCollection->count()){ ?>
	<?php
	$i = 0;
	$total = $brandCollection->count();
	if($show_brand_text){
		echo '<span class="brand-label">'.$brand_text.'</span>';
	}
	?>
	<?php if($brand_layout_listing) { 
		echo '<ul class="product-brands">';
		foreach ($brandCollection as $_brand) {
			?>
			<li class="brand-item">
				<?php if($show_brand_image): ?>
				<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
				<img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a>
				<?php endif; ?>
				<?php if($show_brand_name): ?>
				<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName(); ?></a>
				<?php endif; ?>
				<?php 
				if($show_brand_description){ 
				$_description = $_brand->getDescription();
				?>
				<div class="brand-description">
					<?php echo $this->helper('Ves\Brand\Helper\Data')->filter($_description) ?>
				</div>
				<?php } ?>
			</li>
			<?php
		}
		echo '</ul>';
	} else {
		foreach ($brandCollection as $_brand) { 
		
		?>
			<span class="brand-image">
				<?php if($show_brand_image): ?>
				<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>">
				<img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a>
				<?php endif; ?>
				<?php if($show_brand_name): ?>
				<a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName(); ?></a>
				<?php endif; ?>
			</span>
			<?php 
			if($show_brand_description){ 
			$_description = $_brand->getDescription();
			?>
			<div class="brand-description">
				<?php echo $this->helper('Ves\Brand\Helper\Data')->filter($_description) ?>
			</div>
			<?php } ?>
			<?php if($i<=($total-2)){ echo ', '; }  ?>
			<?php $i++; ?>
	 <?php 
		}
	} 
	?>
<?php } ?>